#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trains
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Trains")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::trains.Properties.Settings.Default.TrainsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Train> Trains
		{
			get
			{
				return this.GetTable<Train>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trains")]
	public partial class Train
	{
		
		private System.Nullable<int> _TrainNo;
		
		private string _TrainName;
		
		private string _Class;
		
		private System.Nullable<int> _TotalBirth;
		
		private System.Nullable<int> _AvailableBirth;
		
		private string _FromStation;
		
		private string _ToStation;
		
		private System.Nullable<decimal> _Price;
		
		public Train()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainNo", DbType="Int")]
		public System.Nullable<int> TrainNo
		{
			get
			{
				return this._TrainNo;
			}
			set
			{
				if ((this._TrainNo != value))
				{
					this._TrainNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainName", DbType="VarChar(100)")]
		public string TrainName
		{
			get
			{
				return this._TrainName;
			}
			set
			{
				if ((this._TrainName != value))
				{
					this._TrainName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="VarChar(50)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this._Class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalBirth", DbType="Int")]
		public System.Nullable<int> TotalBirth
		{
			get
			{
				return this._TotalBirth;
			}
			set
			{
				if ((this._TotalBirth != value))
				{
					this._TotalBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableBirth", DbType="Int")]
		public System.Nullable<int> AvailableBirth
		{
			get
			{
				return this._AvailableBirth;
			}
			set
			{
				if ((this._AvailableBirth != value))
				{
					this._AvailableBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromStation", DbType="VarChar(100)")]
		public string FromStation
		{
			get
			{
				return this._FromStation;
			}
			set
			{
				if ((this._FromStation != value))
				{
					this._FromStation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToStation", DbType="VarChar(100)")]
		public string ToStation
		{
			get
			{
				return this._ToStation;
			}
			set
			{
				if ((this._ToStation != value))
				{
					this._ToStation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
